### DISCUSSION TITLE
Docker compose + Nginx config

### DISCUSSION THREAD

**Discussion by Timbot-42** [arc53/DocsGPT#1328] [Q&A]
I am trying to run DocsGPT on Ubuntu 24.04 with docker compose and Nginx as a reverse proxy to handle the ssl cert. Frontend is loading correctly with ssl cert at https://domain.com. I am running into a problem where frontend can retrieve conversation from backend via /api endpoints upon first load, but when it gets to /stream it gets 404. Also /api/upload works but then when it gets to 100% file uploaded it sends 404.

Has anyone got this setup working and can share some pointers for the config?

I am running nginx as a container included in the docker-compose-azure.yaml file, and using Azure OpenAI environment variables.

**Comment by dartpain** [comment]
How large is the file size? Does the normal chat with default docs work?

**Reply by Timbot-42** [reply]
Hi @dartpain thanks for looking at this. The file is 19MB. I already added the nginx config to allow up to 100M. actually the chat doesnt work at all with any prompt or doc. Its like it can't find the backend for some endpoints.

**Reply by dartpain** [reply]
Yeah its seems to me that this is a backend connection issue,
what is your VITE_API_HOST env var for the frontend?

**Reply by Timbot-42** [reply]
Ok so here is my config. I am using nginx as a container in this case.

My root directory:

/docker-compose-azure.yaml

```
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    restart: always


  frontend:
    build: ./frontend
    environment:
      - VITE_API_HOST=https://mydomain.com
      - VITE_API_STREAMING=true
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./application
    environment:
      - API_KEY=123
      - EMBEDDINGS_KEY=123
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - LLM_NAME=azure_openai
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - OPENAI_API_KEY=123
      - OPENAI_API_BASE=https://myazureurl.com
      - OPENAI_API_VERSION=2023-03-15-preview
      - AZURE_DEPLOYMENT_NAME=gpt-4o-mini
      - AZURE_EMBEDDINGS_DEPLOYMENT_NAME=text-embedding-ada-002
    ports:
      - "7091:7091"
    volumes:
      - ./application/indexes:/app/application/indexes
      - ./application/inputs:/app/application/inputs
      - ./application/vectors:/app/application/vectors
    depends_on:
        - redis
        - mongo
    restart: always

  worker:
    build: ./application
    command: celery -A application.app.celery worker -l INFO
    environment:
      - API_KEY=123
      - EMBEDDINGS_KEY=123
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - API_URL=http://backend:7091
      - OPENAI_API_KEY=123
      - OPENAI_API_BASE=https://myazureurl.com
      - OPENAI_API_VERSION=2023-03-15-preview
      - AZURE_DEPLOYMENT_NAME=gpt-4o-mini
      - AZURE_EMBEDDINGS_DEPLOYMENT_NAME=text-embedding-ada-002
      - LLM_NAME=azure_openai
    depends_on:
        - redis
        - mongo
    restart: always

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    restart: always

  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: always


volumes:
  mongodb_data_container:
```

/nginx.conf

```
events {}

http {
    client_max_body_size 100M;  # Adjust the size as needed

    server {
        listen 80;
        server_name mydomain.com;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name mydomain.com;

        ssl_certificate /etc/nginx/certs/certificate.crt;
        ssl_certificate_key /etc/nginx/certs/private.key;
		
	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

        location / {
            proxy_pass http://frontend:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
```

I wasn't sure which .env to use so used them both
/.env

```
API_KEY=123
EMBEDDINGS_KEY=123
LLM_NAME=azure_openai
VITE_API_STREAMING=true
OPENAI_BASE_URL="https://myazureurl.com"
OPENAI_API_BASE="https://myazureurl.com"
OPENAI_API_VERSION="2023-03-15-preview"
AZURE_DEPLOYMENT_NAME="gpt-4o-mini"
AZURE_EMBEDDINGS_DEPLOYMENT_NAME="text-embedding-ada-002"
```

in application folder

/application/.env

```
API_KEY=123
EMBEDDINGS_KEY=123
LLM_NAME=azure_openai
OPENAI_BASE_URL=https://myazureurl.com
OPENAI_API_BASE=https://myazureurl.com
OPENAI_API_VERSION=2023-03-15-preview
AZURE_DEPLOYMENT_NAME=gpt-4o-mini
MODEL_NAME=gpt-4o-mini
AZURE_EMBEDDINGS_DEPLOYMENT_NAME=text-embedding-ada-002
API_URL=https://mydomain.com
```


I would add that this was working fine running on my local windows machine without nginx, but now I am running nginx on Ubuntu there seems to be some other factors at play. 

Appreciate any help.
Thanks
