### ISSUE TITLE
DocsGPT Deployment in Ubuntu

### ISSUE THREAD

**Issue by frankling2020** [arc53/DocsGPT#213]
### **Basic Information**
- I tried to deploy it in Ubuntu with docker, but it fails to respond always circling though it works in Windows for me.
- It works in Ubuntu when I tried [development environments](https://github.com/arc53/docsgpt#development-environments)
- Query submission succeed in port 5001 but fail in 5173.

### **Environment**:
- system
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```
- repo cloned on Mar 31, 2023.

### **Issue** 
```
frontend_1  | 
frontend_1  | > frontend@0.0.0 dev
frontend_1  | > vite "--host"
frontend_1  | 
frontend_1  | 
frontend_1  |   VITE v4.2.1  ready in 357 ms
frontend_1  | 
frontend_1  |   ?  Local:   http://localhost:5173/
frontend_1  |   ?  Network: http://172.18.0.6:5173/
backend_1   | [2023-04-13 00:58:57 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7)
backend_1   | [2023-04-13 00:58:57 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
backend_1   | [2023-04-13 00:58:57 +0000] [8] [INFO] Worker exiting (pid: 8)
backend_1   | [2023-04-13 00:58:57 +0000] [7] [INFO] Worker exiting (pid: 7)
backend_1   | [2023-04-13 00:58:58 +0000] [69] [INFO] Booting worker with pid: 69
backend_1   | [2023-04-13 00:58:58 +0000] [70] [INFO] Booting worker with pid: 70
```

### **Test**
It works in the following set-up
- use the backend in the development mode
    - `python app.py` in the application folder
- and use the rest in the dockerfile shown below

```
version: "3.3"

services:
  frontend:
    build: ./frontend
    environment:
      - VITE_API_HOST=http://localhost:5001
    ports:
      - "5173:5173"

  worker:
    build: ./application
    command: celery -A app.celery worker -l INFO
    environment:
      - API_KEY=${OPENAI_API_KEY}
      - EMBEDDINGS_KEY=${OPENAI_API_KEY}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - API_URL=http://backend:5001
    depends_on:
        - redis
        - mongo

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db



volumes:
  mongodb_data_container:
```

### Help
Guess: the connection between the backend and others

What will be a solution to this issue?
